general:
  # Commands to run when the WM has started (e.g. to run a script or launch
  # another application). Here we are running a batch script to start Zebar.
  startup_commands: ["shell-exec %userprofile%/.glzr/zebar/start.bat"]

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: "monitor_focus"

gaps:
  # Gap between adjacent windows.
  inner_gap: "8px"

  # Gap between windows and the screen edge.
  outer_gap:
    top: "35px"
    right: "2px"
    bottom: "4px"
    left: "2px"

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: "#8dbcff"

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: "#a1a1a1"

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: "tiling"

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"

window_rules:
  - commands: ["ignore"]
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: "zebar" }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: "PowerToys.PowerAccent" }
      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper*" }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: "super"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["h", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      # Press enter/escape to return to default keybindings.
      - commands: ["wm-disable-binding-mode --name super"]
        bindings: ["escape", "enter"]
      # Change tiling direction. This determines where new tiling windows will
      # be inserted.
      - commands: ["toggle-tiling-direction"]
        bindings: ["t"]
      # Change focus from tiling windows -> floating -> fullscreen.
      - commands: ["wm-cycle-focus"]
        bindings: ["space"]
      # Change the focused window to be floating.
      - commands: ["toggle-floating --centered"]
        bindings: ["f"]
      # Change the focused window to be tiling.
      - commands: ["toggle-tiling"]
        bindings: ["t"]
      # Change the focused window to be fullscreen.
      - commands: ["toggle-fullscreen"]
        bindings: ["z"]
      # Close focused window.
      - commands: ["close"]
        bindings: ["alt+shift+q"]
      # Re-evaluate configuration file.
      - commands: ["wm-reload-config"]
        bindings: ["alt+shift+r"]
      # Redraw all windows.
      - commands: ["wm-redraw"]
        bindings: ["r"]

keybindings:
  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["alt+shift+h", "alt+shift+left"]
  - commands: ["focus --direction right"]
    bindings: ["alt+shift+l", "alt+shift+right"]
  - commands: ["focus --direction up"]
    bindings: ["alt+shift+k", "alt+shift+up"]
  - commands: ["focus --direction down"]
    bindings: ["alt+shift+j", "alt+shift+down"]

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["ctrl+alt+shift+h", "ctrl+alt+shift+left"]
  - commands: ["move --direction right"]
    bindings: ["ctrl+alt+shift+l", "ctrl+alt+shift+right"]
  - commands: ["move --direction up"]
    bindings: ["ctrl+alt+shift+k", "ctrl+alt+shift+up"]
  - commands: ["move --direction down"]
    bindings: ["ctrl+alt+shift+j", "ctrl+alt+shift+down"]

  # Resize focused window by a percentage or pixel amount.
  - commands: ["resize --width -2% --height -2%"]
    bindings: ["alt+shift+-"]
  - commands: ["resize --width +2% --height +2%"]
    bindings: ["alt+shift++"]

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ["wm-enable-binding-mode --name super"]
    bindings: ["alt+shift+;"]

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  - commands: ["shell-exec wezterm"]
    bindings: ["alt+enter"]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace 1"]
    bindings: ["alt+shift+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["alt+shift+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["alt+shift+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["alt+shift+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["alt+shift+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["alt+shift+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["alt+shift+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["alt+shift+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["alt+shift+9"]

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["ctrl+alt+shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["ctrl+alt+shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["ctrl+alt+shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["ctrl+alt+shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["ctrl+alt+shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["ctrl+alt+shift+6"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["ctrl+alt+shift+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["ctrl+alt+shift+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["ctrl+alt+shift+9"]
